### ISSUE TITLE
cannot compile "cp: cannot stat 'build/rose': No such file or directory"

### ISSUE THREAD

**Issue by thecodsman** [mini-rose/rose-browser#49]
OS: artixlinux with runit

error message:
```
$ sudo GTK=4 BUILDTYPE=RELEASE make install
cp -f build/rose /mcc
cp: cannot stat 'build/rose': No such file or directory
make: *** [makefile:32: install] Error 1
```

**Comment by proJM-Coding** [comment]
I am still having this problem with the latest commit. I also get a bunch of errors with `/bin/sh: line 1: c: command not found`. Also is the project still being maintained? The AUR packaged is old and orphaned. Love the project, a star from me!
