### ISSUE TITLE
Plans on adding scroll api function?

### ISSUE THREAD

**Issue by dennis0324** [mini-rose/rose-browser#53]
Hello I really love your project!!

I'm keep searching my default browser for Linux.

I'm willing to use rose-browser for it, and I was wondering that adding API functions about scroll down or up.

Additionally, adding URL Bar toggle API function if possible.

Thank you for making nice app!

**Comment by fenze** [comment]
Hello,

Thank you for your kind words and interest in rose-browser!

I'm glad to inform you that we have recently added scroll functions to the Lua API, and you can find detailed information in the GitHub wiki.

Regarding the URL bar toggle API function, it's on our radar. We're planning to implement it after addressing the majority of the issues on our to-do list.

Thank you for your support and patience. We're working hard to make rose-browser even better!
